### PR TITLE
WIP:feat/tip comment

### PR DESCRIPTION
**Pull request by 97e57e**
i will refactor tip api, after merged this feature

### CODE REVIEW

**Comment by 97e57e** [comment]
good night hm

**Comment by 97e57e** [comment]
@jhaemin 
i changed prisma schema by prisma 2.0.0

**Comment by 97e57e** [comment]
why json change string!!!?!?

**Comment by jhaemin** [comment]
@97e57e I guess it doesn't matter since the JSON type will also be treated as `string` in TypeScript.

**Pull request merged**
